name: Makefile CI

on: release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make
      
    - name: Compress output files
      run: tar -czvf cloudflare-ddns.tar.gz out
      
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: cloudflare-ddns.tar.gz application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
