name: Makefile CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make
      
    - name: Compress output files
      run: zip cloudflare-ddns.zip out
      
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: cloudflare-ddns.zip application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
